cart/urls.py
from django.urls import path, include
from . import views

urlpatterns = [
    path("", views.cart_detail_view, name="cart_detail"),
    path("add/<int:product_id>/", views.add_to_cart_view, name="cart_add"),
    path("remove/<int:product_id>/", views.delete_from_cart, name="cart_remove"),
    path("clear/", views.clear_form, name="cart_clear"),

]

config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('pages.urls')),
    path('accounts/', include('allauth.urls')),
    path("products/", include("products.urls")),
    path("cart/", include("cart.urls")),
    path("order/", include("orders.urls")),

] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

orders/urls.py
from django.urls import path, include
from . import views


urlpatterns = [
    path("create/", views.order_create, name="order_create"),

]

pages/urls.py
from django.urls import path, include

from . import views


urlpatterns = [
    path('', views.home_page, name='home' ),
]

products/urls.py
from django.urls import path, include
from . import views

urlpatterns = [
    path("<str:brand>/", views.list_product, name="listview"),
    path("<int:pk>", views.detail_product, name="detailview"),

]

accounts/models.py
from django.contrib.auth.models import AbstractUser
from django.db import models


class CustomUser(AbstractUser):
    age = models.DateField(null=True, blank=True)

cart/models.py
from django.db import models

# Create your models here.

orders/models.py
from django.db import models
from django.contrib.auth import get_user_model
from django.utils.translation import gettext as _


class Order(models.Model):
    user = models.ForeignKey(get_user_model(), on_delete=models.CASCADE, verbose_name=_("User"))
    is_paid = models.BooleanField(default=False, verbose_name=_("Is paid?"))
    name = models.CharField(max_length=400, verbose_name=_("Name"))
    family_name = models.CharField(max_length=400, verbose_name=_("Family name"))
    phone_number = models.CharField(max_length=15, verbose_name=_("Phone number"))
    address = models.CharField(max_length=700, verbose_name=_("Address"))
    order_note = models.TextField(blank=True, verbose_name=_("Order Note"))
    datetime_created = models.DateTimeField(auto_now_add=True, verbose_name=_("Created"))
    datetime_edited = models.DateTimeField(auto_now=True, verbose_name=_("Modified"))

    def __str__(self):
        return f"Order {self.id}"

    def get_total_price(self):
        return sum(item.quantity * item.price for item in self.items.all())


class OrderItem(models.Model):
    order = models.ForeignKey(Order, on_delete=models.CASCADE, related_name="items")
    product = models.ForeignKey("products.Product", on_delete=models.CASCADE, related_name="order_items")
    quantity = models.PositiveIntegerField(default=1)
    price = models.PositiveIntegerField()

    def __str__(self):
        return f"OrderItem {self.id} for product {self.product}"

    def get_total_price_each_item(self):
        return self.quantity * self.price

persian_translation/models.py
from django.db import models

# Create your models here.

products/models.py
from django.db import models
from django.utils.translation import gettext_lazy as _

class Product(models.Model):
    FARSI_MENU = {
        ("D", _("Darad")),
        ("N", _("Nadarad")),

    }
    name = models.CharField(max_length=1000, default="lorem ipsum")
    brand = models.CharField(max_length=80)
    image = models.ImageField(upload_to='products/', blank=False, null=False)
    category = models.CharField(max_length=80)
    color = models.CharField(max_length=80)
    guarantee = models.CharField(max_length=100)
    description = models.CharField(max_length=1500)
    price = models.PositiveIntegerField(default=0)
    chip = models.CharField(max_length=100)
    screen_size = models.CharField(max_length=50)
    internal_storage = models.CharField(max_length=50)
    ram_storage = models.CharField(max_length=50)
    camera_quality = models.CharField(max_length=50)
    battery_capacity = models.CharField(max_length=80)
    farsi_menu = models.CharField(max_length=10, choices=FARSI_MENU)

    def __str__(self):
        return self.brand

accounts/forms.py
from django.contrib.auth.forms import UserCreationForm, UserChangeForm


from .models import CustomUser

class CustomUserCreationForm(UserCreationForm):
    class Meta:
        model = CustomUser
        fields = ("email", "username", "age")

class CustomUserChangeForm(UserChangeForm):
    class Meta:
        model = CustomUser
        fields = ("email", "username", "age")

cart/forms.py
from django import forms


class AddToCartProductForm(forms.Form):
    QUANTITY_CHOICES = [(i, str(i)) for i in range(1, 31)]

    quantity = forms.TypedChoiceField(choices=QUANTITY_CHOICES, coerce=int)
    inplace = forms.BooleanField(required=False, widget=forms.HiddenInput)

orders/forms.py
from django import forms
from .models import Order


class OrderForm(forms.ModelForm):
    class Meta:
        model = Order
        fields = ["name", "family_name", "phone_number", "address", "order_note"]

cart/views.py
from django.shortcuts import render, HttpResponse, get_object_or_404, redirect
from django.views.decorators.http import require_POST
from django.contrib import messages
from django.utils.translation import gettext as _
from products.models import Product
from .cart import Cart
from .forms import AddToCartProductForm


def cart_detail_view(request):
    cart = Cart(request)

    for item in cart:
        item["product_update_quantity_form"] = AddToCartProductForm(initial={
            "quantity": item["quantity"],
            "inplace": True
        })

    return render(request, "cart/cart_detail.html", {
        'cart': cart
    })


@require_POST
def add_to_cart_view(request, product_id):
    cart = Cart(request)

    product = get_object_or_404(Product, id=product_id)
    form = AddToCartProductForm(request.POST)
    if form.is_valid():
        cleaned_data = form.cleaned_data
        quantity = cleaned_data["quantity"]
        replace_current_quantity = cleaned_data["inplace"]
        cart.add(product, quantity, replace_current_quantity)
    return redirect("home")


def delete_from_cart(request, product_id):
    cart = Cart(request)

    product = get_object_or_404(Product, id=product_id)
    cart.remove(product)
    return redirect("home")


def clear_form(request):
    cart = Cart(request)
    cart.clear()
    messages.success(request, _("Your cart has been cleared successfully"))
    return redirect("home")

orders/views.py
from django.conf import settings
from django.shortcuts import render, redirect
from django.contrib.auth.decorators import login_required
from django.contrib import messages
from django.utils.translation import gettext as _
from .forms import OrderForm
from .models import OrderItem
from cart.cart import Cart


@login_required
def order_create(request):
    order_from = OrderForm()
    cart = Cart(request)

    if len(cart) == 0:
        messages.warning(request, _("Your cart is empty please purchase something"))
        return redirect("listview")

    if request.method == "POST":
        order_form = OrderForm(request.POST)
        if order_form.is_valid():
            order_obj = order_form.save(commit=False)
            order_obj.user = request.user
            order_obj.save()

            for item in cart:
                product = item["product_obj"]
                OrderItem.objects.create(
                    order=order_obj,
                    product=product,
                    quantity=item["quantity"],
                    price=product.price,
                )
            cart.clear()

    return render(request, "orders/order_create.html", context={
        "form": order_from,
    })

pages/views.py
from django.shortcuts import render



def home_page(request):
    return render(request, 'home.html')

persian_translation/views.py
from django.shortcuts import render

# Create your views here.

products/views.py
from django.shortcuts import render, get_object_or_404

from .models import Product
from cart.forms import AddToCartProductForm


def list_product(request, brand):
    products = Product.objects.filter(brand__iexact= brand)
    return render(request, 'products/list_view.html', {'products': products})


def detail_product(request, pk):
    product = get_object_or_404(Product, pk=pk)
    return render(request, 'products/detail_view.html', {'product': product, "add_to_cart": AddToCartProductForm()})

orders/templates/orders/order_create.html
{% load static %}
{% load humanize %}
{% load persian_translation_tags %}

<!DOCTYPE html>
<html lang="fa" dir="rtl">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>ثبت سفارش</title>
    <link rel="icon" type="image/png" href="../image/svg/mobile.svg">
    <link rel="stylesheet" href="{% static 'order/app.css'  %}">
</head>
<body>
    <div class="order"> 
        <div class="container">
            <div class="row">
                <div class="col-6">
                    <h2>جزئیات سفارش</h2>
                    <div class="checkout-form">
                        <form  method="POST" class="form" action="#">
                            {% csrf_token %}
                            <div class="form-row mb--20">
                                <div class="form__group col-5">
                                    <label for="billing_fname" class="form__label">نام <span class="required">*</span></label>
                                    <input type="text" name="name" id="billing_fname" class="form__input">
                                </div>
                                <div class="form__group form__group--right col-5">
                                    <label for="billing_lname" class="form__label">نام خانوادگی <span class="required">*</span></label>
                                    <input type="text" name="family_name" id="billing_lname" class="form__input form__input--2">
                                </div>
                            </div>
                            <div class="form-row mb--20">
                                <div class="form__group col-12">
                                    <label for="billing_company" class="form__label">آدرس</label>
                                    <input type="text" name="address" id="billing_company" class="form__input">
                                </div>
                            </div>
                            <div class="form-row mb--20">
                                <div class="form__group col-12">
                                    <label for="billing_phone" class="form__label">شماره همراه <span class="required">*</span></label>
                                    <input type="text" name="phone_number" id="billing_phone" class="form__input">
                                </div>
                            </div>
                            <div class="form-row">
                                <div class="form__group col-12">
                                    <label for="orderNotes" class="form__label form__label--2">یادداشت شما</label>
                                    <textarea class="form__input form__input--textarea" id="orderNotes" name="order_note" placeholder="اگر یادداشتی دارید در اینجا وارد کنید. در غیر این صورت این مکان را خالی بگذارید"></textarea>
                                </div>
                            </div>
                            <button type="submit" class="send__data">ارسال</button>
                        </form>
                    </div>
                </div>
                <div class="col-6">
                    <div class="order-details">
                        <h2>سفارش شما</h2>
                        <ul class="list-unstyled cd-cart-items shopping-cart-top">
                            {% for item in cart %}
                                <li>
                                    <a class="img__cnt" href="../products/apple/information1/informatin1.html">
                                        <img class="img__apple" src="{{ item.product_obj.image.url }}" alt="apple_img1">
                                    </a>
                                    <a class="product__description" href="../products/apple/information1/informatin1.html">
                                        {{ item.product_obj.name }}
                                    </a>
                                   <div class="price_area">
                                        <div class="new_price">{{ item.product_obj.price|intcomma:False|translate_number }} تومان</div>
                                   </div>
                                </li>
                            {% endfor %}
{#                            <div class="total">#}
{#                                <h3>مجموع</h3>#}
{#                                <span> تومان</span>#}
{#                            </div>#}
                            <div class="checkout-payment">
                                <h3>روش پرداخت</h3>
                                <form action="#" class="payment-form">
                                    <div class="payment-radio">
                                            <input type="radio" value="bank" name="payment-method" id="bank" checked="">
                                            <label class="payment-label" for="cheque">درگاه آنلاین زرین پال</label>
                                    </div>
                                </form>
                            </div>
                        </ul>
                    </div>
                </div>
            </div>
        </div>
    </div>

    
</body>
</html>

products/templates/products/detail_view.html
{% load static %}
{% load i18n %}
{% load persian_translation_tags %}
{% load humanize %}

<!DOCTYPE html>
<html lang="fa" dir="rtl">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Information product</title>
    <link rel="stylesheet" href="{% static 'information/app.css' %}">
    <link rel="icon" type="image/png" href="../images/svg/mobile.svg">
</head>
<body>
<div class="wrapper__login__bying__search">
    <div class="search">
        <form id="formsearch" class="searchform" action="#" method="get">
            <button type="submit" class="search_btn">
                <svg xmlns="http://www.w3.org/2000/svg" width="20" height="20" viewBox="-1 -1 24 24"
                "="" stroke="#0ABEAD">
                <path d="M24.852,24.2l-6.993-7.294a9.882,9.882,0,1,0-.7.636l7.009,7.312a.47.47,0,0,0,.665.013A.473.473,0,0,0,24.852,24.2ZM10.865,18.88a8.968,8.968,0,1,1,8.941-8.968A8.965,8.965,0,0,1,10.865,18.88Z"
                      transform="translate(-0.983)"></path>
                </svg>
            </button>
            <input type="text" name="keyword" placeholder="نام محصول مورد نظر را وارد کنید"
                   class="search_inp search__inppp" id="advancedSearchInput" autocomplete="off">
        </form>
    </div>
    <ul class="wrapper__login__bying">
        <li class="nav__left--login">
            <a class="login__link" href="C:/Users/amirh/Desktop/MyProject/login/login.html">
                <svg class="login__link--logo" xmlns="http://www.w3.org/2000/svg" width="50" height="40" fill="none"
                     viewBox="0 0 24 24" id="login">
                    <path fill="#000" fill-rule="evenodd"
                          d="M9 4C9 2.89543 9.89543 2 11 2H20C21.1046 2 22 2.89543 22 4V20C22 21.1046 21.1046 22 20 22H11C9.89543 22 9 21.1046 9 20V15.5C9 15.2239 8.77614 15 8.5 15C8.22386 15 8 15.2239 8 15.5V20C8 21.6569 9.34315 23 11 23H20C21.6569 23 23 21.6569 23 20V4C23 2.34315 21.6569 1 20 1H11C9.34315 1 8 2.34315 8 4V8.5C8 8.77614 8.22386 9 8.5 9C8.77614 9 9 8.77614 9 8.5V4ZM17.8536 12.3536L12.8536 17.3535C12.6584 17.5488 12.3418 17.5488 12.1465 17.3536C11.9512 17.1583 11.9512 16.8417 12.1465 16.6464L16.2929 12.5H1.5C1.22386 12.5 1 12.2761 1 12C1 11.7239 1.22386 11.5 1.5 11.5H16.2929L12.1465 7.35355C11.9512 7.15829 11.9512 6.84171 12.1465 6.64644C12.3418 6.45118 12.6584 6.45119 12.8536 6.64645L17.8536 11.6464C18.0488 11.8417 18.0488 12.1583 17.8536 12.3536Z"
                          clip-rule="evenodd"></path>
                </svg>
            </a>
        </li>
        <li class="nav__left--bying">
            <a class="nav__btn">
                <svg class="nav__left--logo" xmlns="http://www.w3.org/2000/svg" width="50" height="50" fill="none"
                     viewBox="0 0 128 128" id="shopping-cart">
                    <circle cx="49" cy="107" r="5" fill="#000"></circle>
                    <circle cx="87" cy="107" r="5" fill="#000"></circle>
                    <path stroke="#000" stroke-linecap="round" stroke-linejoin="round" stroke-width="6"
                          d="M43.116 77H80.0627C87.276 77 90.8827 77 93.7816 75.2093C96.6806 73.4186 98.3028 70.178 101.547 63.6968V63.6968C109.382 48.045 113.3 40.2192 109.783 34.5255C106.266 28.8319 97.5594 28.8319 80.1468 28.8319H32.0126M43.116 77L32.2617 29.8155L31.3089 26.0536C30.2073 21.7046 29.6566 19.5301 28.0311 18.2651C26.4057 17 24.1625 17 19.6762 17H16M43.116 77H39.7626C35.4824 77 32.0126 80.4698 32.0126 84.75V84.75C32.0126 89.0302 35.4824 92.5 39.7626 92.5H94.8878"></path>
                </svg>
            </a>
        </li>
    </ul>
</div>
<div class="nav-menu">
    <span class="close-btn">x</span>
    <h2 class="nav-menu__title">سبد خرید</h2>
    <!-- <ul class="list-menu">

        <div class="error">سبد خرید شما خالی می باشد.</div>
    </ul> -->
    <div class="basketProgress">

    </div>
    <ul class="list-unstyled cd-cart-items shopping-cart-top">
        <li>
            <a class="img__cnt"
               href="file:///C:/Users/amirh/Desktop/MyProject/products/apple/information1/informatin1.html">
                <img class="img__apple" src="file:///C:/Users/amirh/Desktop/MyProject/products/apple/images/img1.png"
                     alt="apple_img1">
            </a>
            <a class="product__description"
               href="file:///C:/Users/amirh/Desktop/MyProject/products/apple/information1/informatin1.html">
                {{ product.name }}
            </a>
            <div class="container__quantity">
                <span class="count">تعداد :</span>
                <div class="product-quantity">
                    <button onclick="this.nextElementSibling.stepDown()">-</button>
                    <input class="quantity__input" type="number" value="1" min="1" max="10">
                    <button onclick="this.previousElementSibling.stepUp()">+</button>
                </div>
            </div>
            <div class="remove__container">
                <a class="remove" href="#">
                    <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 48 48" width="20" height="20" id="trashcan">
                        <path d="M10.71,43.24A2.27,2.27,0,0,0,13,45.5H35a2.26,2.26,0,0,0,2.26-2.26l1.38-28.45H9.33ZM31.44,19.83h3.17l-.93,19.34a1.58,1.58,0,1,1-3.16,0Zm-9,0h3.16V39.17a1.58,1.58,0,0,1-3.16,0Zm-9,0h3.17l.92,19.34a1.58,1.58,0,0,1-3.16,0Zm25.17-13H29.78c0-.11,0-.21,0-.32V5.36c0-1.58-1-2.86-2.19-2.86H20.39c-1.21,0-2.19,1.28-2.19,2.86V6.5c0,.11,0,.21,0,.32H9.44c-1.21,0-2.19,1.27-2.19,2.85v4h33.5v-4C40.75,8.09,39.77,6.82,38.56,6.82Zm-18.9,0a2.29,2.29,0,0,1,2-1.89h4.6a2.29,2.29,0,0,1,2,1.89Z"
                              fill="#eb0e17" class="color000000 svgShape"></path>
                    </svg>
                    حذف
                </a>
            </div>
            <div class="price_area">
                <div class="new_price">{{ product.price }} تومان</div>
            </div>
        </li>
    </ul>
    <a class="btn" href="file:///C:/Users/amirh/Desktop/MyProject/order-registration/order.html" title="">
        <span> ثبت سفارش</span>
    </a>
</div>
<div class="single__product">
    <div class="single__product__gallery">
        <h2 class="title">اطلاعلات نهایی و خرید محصول</h2>
        <a class="link__gallery" href="../images/img6.png">
            <img class="img__gallery" src="{{ product.image.url }}" alt="product1">
        </a>
        <div class="shopping">
            {#                <div class="product__offer">#}
            {#                    <span class="product__offer-percent">3%</span>#}
            {#                    <span class="product_offer-price">۹۷,۱۱۱,۰۰۰</span>#}
            {#                </div>#}
            <div class="single__price">
                    <span class="single__price--new">
                        {{ product.price|intcomma:False|translate_number }}
                        تومان
                    </span>
            </div>
            <div class="single__shopping">
                <form action="{% url 'cart_add' product.id %}" method="POST">
                    {% csrf_token %}
                    {{ add_to_cart.as_p }}
                    <div style="display: flex; justify-content: center;">
                        <button

                                class="single__shopping__link"
                                type="submit">
                                افزودن به سبد خرید
                        </button>
                    </div>
                </form>
{#                                    <a class="single__shopping__link" href="#">#}
{#                                        <svg class="shopping__cart__svg" xmlns="http://www.w3.org/2000/svg" width="23.411" height="24" viewBox="0 0 23.411 24">#}
{#                                            <path id="Path_7533" data-name="Path 7533" d="M22.713,4.077A2.993,2.993,0,0,0,20.41,3H4.242L4.2,2.649A3,3,0,0,0,1.222,0H1A1,1,0,0,0,1,2h.222a1,1,0,0,1,.993.883l1.376,11.7A5,5,0,0,0,8.557,19H19a1,1,0,0,0,0-2H8.557a3,3,0,0,1-2.82-2h11.92a5,5,0,0,0,4.921-4.113l.785-4.354a2.994,2.994,0,0,0-.65-2.456ZM21.4,6.178l-.786,4.354A3,3,0,0,1,17.657,13H5.419L4.478,5H20.41a1,1,0,0,1,.99,1.178Z" fill="#fff"></path>#}
{#                                            <circle id="Ellipse_1" data-name="Ellipse 1" cx="2" cy="2" r="2" transform="translate(5 20)" fill="#fff">#}
{#                                            </circle>#}
{#                                            <circle id="Ellipse_2" data-name="Ellipse 2" cx="2" cy="2" r="2" transform="translate(15 20)" fill="#fff">#}
{#                                            </circle>#}
{#                                        </svg>#}
{#                                        افزودن به سبد خرید#}
{#                                    </a>#}
            </div>
        </div>
    </div>

    <div class="single__product__info">
        <div class="single__product__headline">
            <h1 class="single__product__headline__upper">
                {{ product.name }}
            </h1>
        </div>
        <div class="single__product__directory">
            <ul class="list-unstyled">
                <li class="list__unstyled__item">
                    برند : <span class="bold__directory">{{ product.brand }}</span>
                </li>
                <li class="list__unstyled__item">
                    دسته بندی : <span class="bold__directory">گوشی موبایل</span>
                </li>
                <li class="list__unstyled__item">
                    رنگ : <span class="bold__directory">{{ product.color }}</span>
                </li>
                <li class="list__unstyled__item">
                    گارانتی : <span class="bold__directory">{{ product.guarantee }}</span>
                </li>
            </ul>
        </div>
        <div class="wrapper__directory2__shopping">
            <div class="single__product__directory2">
                <ul class="directory2__caption">
                    <li>
                        <div class="directory2__text" style="min-height: 30px;line-height: 30px;">
                            توضیحات سفارش :
                            {{ product.description }}
                        </div>
                    </li>
                    <li>
                        <div class="directory2__text" style="min-height: 30px;line-height: 30px;">
                            تراشه پردازنده :
                            {{ product.chip }}
                        </div>
                    </li>
                    <li>
                        <div class="directory2__text" style="min-height: 30px;line-height: 30px;">
                            اندازه صفحه نمایش :
                            {{ product.screen_size }}
                        </div>
                    </li>
                    <li>
                        <div class="directory2__text" style="min-height: 30px;line-height: 30px;">
                            حافظه داخلی :
                            {{ product.internal_storage }}
                        </div>
                    </li>
                    <li>
                        <div class="directory2__text" style="min-height: 30px;line-height: 30px;">
                            حافظه رم :
                            {{ product.ram_storage }}
                        </div>
                    </li>
                    <li>
                        <div class="directory2__text" style="min-height: 30px;line-height: 30px;">
                            کیفیت دوربین :
                            {{ product.camera_quality }}
                        </div>
                    </li>
                    <li>
                        <div class="directory2__text" style="min-height: 30px;line-height: 30px;">
                            ظرفیت باتری :
                            {{ product.battery_capacity }}
                        </div>
                    </li>
                    <li>
                        <div class="directory2__text" style="min-height: 30px;line-height: 30px;">
                            منوی فارسی :
                            {{ product.get_farsi_menu_display }}
                        </div>
                    </li>
                </ul>
            </div>

        </div>
    </div>
</div>
<script src="./scripts/app.js"></script>
</body>
</html>

products/templates/products/list_view.html
{% load static %}
{% load persian_translation_tags %}
{% load humanize %}


<!DOCTYPE html>
<html lang="fa" dir="rtl">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Apple products</title>
    <link rel="stylesheet" href="{% static 'products/app.css' %}">
    <link rel="stylesheet" href="{% static 'products/responsive.css' %}">
    <link rel="icon" type="image/png" href="../apple/images/svg/mobile.svg">
</head>
<body>
<div class="container">
    <div class="heaeder__container">
        <div class="section-title">
            <h3 class="section-title_h">
                <svg class="section__title-icon" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24"
                     fill="currentColor">
                    <path fill-rule="evenodd"
                          d="M11.47 13.28a.75.75 0 0 0 1.06 0l7.5-7.5a.75.75 0 0 0-1.06-1.06L12 11.69 5.03 4.72a.75.75 0 0 0-1.06 1.06l7.5 7.5Z"
                          clip-rule="evenodd"/>
                    <path fill-rule="evenodd"
                          d="M11.47 19.28a.75.75 0 0 0 1.06 0l7.5-7.5a.75.75 0 1 0-1.06-1.06L12 17.69l-6.97-6.97a.75.75 0 0 0-1.06 1.06l7.5 7.5Z"
                          clip-rule="evenodd"/>
                </svg>
                جدیدترین محصولات iphone
            </h3>
        </div>
        <div class="nav__left--login">
            <a class="login__link" href="{% url 'account_login' %}">
                ورود | ثبت نام
            </a>
        </div>
    </div>
    <div class="row">
        {% for product in products %}
            <div class="product">
                <img class="product__image" src="{{ product.image.url }}" alt="product1">
                <h4 class="product__name">
                    <a href="{% url 'detailview' product.id %}" class="product__link"> {{ product.description }} </a>
                </h4>
                <div class="product__price">
                   <span class="product__price-number">{{ product.price|intcomma:False|translate_number }}</span>
                   <span class="product__price-unit">تومان</span>
                </div>
{#                <div class="product__rating">#}
{#                    <span class="product__rating-number">5</span>#}
{#                    <svg class="product__rating-icon" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" fill="currentColor">#}
{#                       <path fill-rule="evenodd" d="M10.788 3.21c.448-1.077 1.976-1.077 2.424 0l2.082 5.006 5.404.434c1.164.093 1.636 1.545.749 2.305l-4.117 3.527 1.257 5.273c.271 1.136-.964 2.033-1.96 1.425L12 18.354 7.373 21.18c-.996.608-2.231-.29-1.96-1.425l1.257-5.273-4.117-3.527c-.887-.76-.415-2.212.749-2.305l5.404-.434 2.082-5.005Z" clip-rule="evenodd" />#}
{#                     </svg>#}
{#                  </div>#}
                <a class="link__buttom buttom" href="{% url 'detailview' product.id %}">مشاهده بیشتر</a>
            </div>
        {% endfor %}
    </div>
</body>
</html>